# Generated by Django 3.0.3 on 2020-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField()),
                ('isMale', models.BooleanField()),
                ('isFemale', models.BooleanField()),
                ('weight', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=30)),
                ('isActive', models.BooleanField()),
                ('isnotActive', models.BooleanField()),
                ('isModeratelyActive', models.BooleanField()),
            ],
        ),
    ]
