# Generated by Django 3.0.3 on 2020-02-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('diet', models.CharField(max_length=300)),
                ('to_eat', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='healthmodel',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='healthmodel',
            name='diseases',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
