# Generated by Django 3.0.3 on 2020-02-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietmanager', '0002_auto_20200229_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmodel',
            name='diseases',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
