# Generated by Django 3.0.3 on 2020-02-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietmanager', '0004_remove_healthmodel_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmodel',
            name='diseases',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
