# Generated by Django 3.0.3 on 2020-02-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietmanager', '0006_auto_20200229_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmodel',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='healthmodel',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='healthmodel',
            name='proteins',
            field=models.FloatField(default=0),
        ),
    ]
