# Generated by Django 3.0.3 on 2020-02-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietmanager', '0007_auto_20200229_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmodel',
            name='diet',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
