# Generated by Django 3.0.3 on 2020-02-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietmanager', '0008_healthmodel_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmodel',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
