# Generated by Django 3.0.3 on 2020-02-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietmanager', '0009_auto_20200229_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmodel',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
