# Generated by Django 3.0.3 on 2020-02-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietmanager', '0010_auto_20200229_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietmanager.HealthModel'),
        ),
    ]
